# Generated by Django 4.2 on 2023-04-23 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_follow_profile_users_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='users_following',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replylike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.AddField(
            model_name='contact',
            name='contacted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.profile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacted_by', to='userprofile.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, through='userprofile.Contact', to='userprofile.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('contacts', 'contacted_by')},
        ),
    ]
