# Generated by Django 4.2 on 2023-04-23 21:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0009_usercontacts_delete_contact_alter_profile_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontacts',
            old_name='user',
            new_name='contact',
        ),
        migrations.AlterUniqueTogether(
            name='usercontacts',
            unique_together={('profile', 'contact')},
        ),
    ]
