# Generated by Django 4.2 on 2023-04-30 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_alter_profile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postalbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumpic', models.ImageField(default='default.jpg', upload_to='post_album')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.post')),
            ],
        ),
    ]
