# Generated by Django 4.2 on 2023-05-05 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0014_postimage_remove_post_picture_alter_post_likes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usercontacts',
            new_name='UserContact',
        ),
    ]
