# Generated by Django 4.2 on 2023-05-25 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_userexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexperience',
            name='enterprise',
        ),
    ]
