# Generated by Django 4.2 on 2023-07-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0022_poll_polloption_alter_profile_image_voter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='votepercentage',
        ),
    ]
