# Generated by Django 4.2 on 2023-08-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_remove_polloption_votepercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
