# Generated by Django 4.2 on 2023-09-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0025_postimage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
