# Generated by Django 4.2 on 2023-09-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_alter_postimage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='created_at',
        ),
    ]
